name: Cucumber Api Tests Manual

on: workflow_dispatch

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run scenarios with Maven
        run: mvn clean test
      - name: Upload cucumber report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report-html
          path: target/cucumber.html