name: Cucumber Api Tests Manual

on: workflow_dispatch

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run scenarios with Maven
        run: mvn clean test
      - name: Upload cucumber report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report-html
          path: target/cucumber.html
      - name: Copy report to server
        if: always()
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 18.159.59.162
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: target/cucumber.html
          strip_components: 1
          target: /var/www/html/cucumber
